# This file is automatically generated

$c->{fields}->{eprint} = [] if !defined $c->{fields}->{eprint};
push @{$c->{fields}->{eprint}},
{
    allow_null => 1,
    browse_link => 'date',
    export_as_xml => 1,
    input_boxes => 1,
    input_cols => 10,
    input_ordered => 1,
    maxlength => 10,
    min_resolution => 'year',
    multiple => 0,
    name => 'date',
    provenance => 'user',
    required => 1,
    sql_index => 1,
    type => 'date',
    volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'job_identifier',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  family_first => 1,
  fields => [
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_cols => 20,
                  input_ordered => 1,
                  maxlength => 64,
                  sql_index => 0,
                  sub_name => 'family',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_cols => 20,
                  input_ordered => 1,
                  maxlength => 64,
                  sql_index => 0,
                  sub_name => 'given',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_cols => 8,
                  input_ordered => 1,
                  maxlength => 10,
                  sql_index => 0,
                  sub_name => 'lineage',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_cols => 8,
                  input_ordered => 1,
                  maxlength => 40,
                  sql_index => 0,
                  sub_name => 'honourific',
                  type => 'text'
                }
              ],
  hide_honourific => 0,
  hide_lineage => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 1,
  name => 'person_shown',
  browse_link => 'vips',
  provenance => 'user',
  'render_order' => 'gf',
  required => 0,
  sql_index => 1,
  type => 'name',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'organisation',
  provenance => 'user',
  required => 0,
  sql_index => 1,
  type => 'text',
  browse_link => 'organisations',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'event',
  provenance => 'user',
  browse_link => 'events',
  required => 0,
  sql_index => 1,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  min_resolution => 'year',
  multiple => 0,
  name => 'date_artwork',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'date',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'source_artwork',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'source_ID_artwork',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
    name => "tags",
    type => "text",
    multiple => 1,
    export_as_xml => 0,
}
,{
    name => "keywords",
    type => "subject",
    multiple => 1,
    top => "eprint_tags",
    browse_link => "collections",
    export_as_xml => 1,
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  input_rows => 10,
  maxlength => 65535,
  multiple => 0,
  name => 'copyright_artwork',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'longtext',
  volatile => 0
}
,{
  allow_null => 1,
  browse_link => 'divisions',
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 0,
  input_rows => 10,
  input_style => 0,
  maxlength => 255,
  name => 'divisions',
  provenance => 'user',
  required => 1,
  sql_index => 0,
  top => 'divisions',
  type => 'subject',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  input_rows => 10,
  maxlength => 65535,
  multiple => 0,
  name => 'official_url',
  provenance => 'user',
  render_value => 'EPrints::Extras::render_url_truncate_end',
  required => 0,
  sql_index => 0,
  type => 'url',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'title_artwork',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 0,
  input_rows => 10,
  input_style => 'short',
  maxlength => 255,
  multiple => 0,
  name => 'full_text_status',
  provenance => 'user',
  required => 1,
  set_name => 'eprints_security',
  sql_index => 0,
  type => 'namedset',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  family_first => 1,
  fields => [
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_boxes => 1,
                  input_cols => 20,
                  input_ordered => 1,
                  maxlength => 64,
                  provenance => 'user',
                  sql_index => 0,
                  sub_name => 'family',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_boxes => 1,
                  input_cols => 20,
                  input_ordered => 1,
                  maxlength => 64,
                  provenance => 'user',
                  sql_index => 0,
                  sub_name => 'given',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_boxes => 1,
                  input_cols => 8,
                  input_ordered => 1,
                  maxlength => 10,
                  provenance => 'user',
                  sql_index => 0,
                  sub_name => 'lineage',
                  type => 'text'
                },
                {
                  allow_null => 1,
                  export_as_xml => 1,
                  input_boxes => 1,
                  input_cols => 8,
                  input_ordered => 1,
                  maxlength => 10,
                  provenance => 'user',
                  sql_index => 0,
                  sub_name => 'honourific',
                  type => 'text'
                }
              ],
  hide_honourific => 1,
  hide_lineage => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 1,
  name => 'creator_artwork',
  provenance => 'user',
  render_order => 'gf',
  required => 0,
  sql_index => 0,
  type => 'name',
  volatile => 0
}
,{
  allow_null => 1,
  browse_link => 'subjects',
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 0,
  input_rows => 10,
  input_style => 0,
  maxlength => 255,
  multiple => 1,
  name => 'subjects',
  provenance => 'user',
  required => 1,
  sql_index => 1,
  top => 'subject',
  type => 'subject',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'credit_line',
  provenance => 'user',
  required => 1,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'copyright_notice',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,{
  allow_null => 1,
  export_as_xml => 1,
  input_boxes => 1,
  input_cols => 60,
  input_ordered => 1,
  maxlength => 255,
  multiple => 0,
  name => 'right_usage',
  provenance => 'user',
  required => 0,
  sql_index => 0,
  type => 'text',
  volatile => 0
}
,;
