# This file is automatically generated

$c->{fields}->{document} = [] if !defined $c->{fields}->{document};
push @{$c->{fields}->{document}}, 
	{
  'allow_null' => '1',
  'export_as_xml' => '1',
  'input_boxes' => 3,
  'input_cols' => 6,
  'input_ordered' => 1,
  'maxlength' => 255,
  'multiple' => '0',
  'name' => 'price',
  'provenance' => 'user',
  'required' => '0',
  'sql_index' => '0',
  'type' => 'int',
  'volatile' => '0'
},
;
