# This file is automatically generated

$c->{fields}->{user} = [] if !defined $c->{fields}->{user};
push @{$c->{fields}->{user}}, 
	{
  'allow_null' => '1',
  'export_as_xml' => '1',
  'input_boxes' => 3,
  'input_cols' => 60,
  'input_ordered' => 0,
  'input_rows' => 10,
  'input_style' => 0,
  'maxlength' => 255,
  'multiple' => '0',
  'name' => 'dept',
  'provenance' => 'user',
  'required' => '1',
  'sql_index' => '1',
  'top' => 'divisions',
  'type' => 'subject',
  'volatile' => '0'
}
,{
  'allow_null' => '1',
  'export_as_xml' => '1',
  'family_first' => '1',
  'fields' => [
                {
                  'allow_null' => 1,
                  'export_as_xml' => 1,
                  'input_boxes' => 3,
                  'input_cols' => 20,
                  'input_ordered' => 1,
                  'maxlength' => 64,
                  'sql_index' => 0,
                  'sub_name' => 'family',
                  'type' => 'text'
                },
                {
                  'allow_null' => 1,
                  'export_as_xml' => 1,
                  'input_boxes' => 3,
                  'input_cols' => 20,
                  'input_ordered' => 1,
                  'maxlength' => 64,
                  'sql_index' => 0,
                  'sub_name' => 'given',
                  'type' => 'text'
                },
                {
                  'allow_null' => 1,
                  'export_as_xml' => 1,
                  'input_boxes' => 3,
                  'input_cols' => 8,
                  'input_ordered' => 1,
                  'maxlength' => 10,
                  'sql_index' => 0,
                  'sub_name' => 'lineage',
                  'type' => 'text'
                },
                {
                  'allow_null' => 1,
                  'export_as_xml' => 1,
                  'input_boxes' => 3,
                  'input_cols' => 8,
                  'input_ordered' => 1,
                  'maxlength' => 10,
                  'sql_index' => 0,
                  'sub_name' => 'honourific',
                  'type' => 'text'
                }
              ],
  'hide_honourific' => '1',
  'hide_lineage' => '1',
  'input_boxes' => 3,
  'input_cols' => 60,
  'input_ordered' => 1,
  'maxlength' => 255,
  'multiple' => '0',
  'name' => 'name',
  'provenance' => 'user',
  'render_order' => 'fg',
  'required' => '1',
  'sql_index' => '1',
  'type' => 'name',
  'volatile' => '0'
}
,{
  'allow_null' => '1',
  'export_as_xml' => '0',
  'input_boxes' => 3,
  'input_cols' => 60,
  'input_ordered' => 1,
  'input_rows' => 10,
  'input_style' => 'radio',
  'maxlength' => 255,
  'multiple' => '0',
  'name' => 'hideemail',
  'provenance' => 'user',
  'required' => '0',
  'sql_index' => '0',
  'type' => 'boolean',
  'volatile' => '0'
}
,{
  'allow_null' => '1',
  'export_as_xml' => '1',
  'input_boxes' => 3,
  'input_cols' => 60,
  'input_ordered' => 1,
  'maxlength' => 255,
  'name' => 'jobtitle',
  'provenance' => 'user',
  'required' => '0',
  'sql_index' => '0',
  'type' => 'text',
  'volatile' => '0'
}
,{
  'allow_null' => '1',
  'export_as_xml' => '1',
  'input_boxes' => '3',
  'input_cols' => '60',
  'input_ordered' => '1',
  'input_rows' => '10',
  'maxlength' => 65535,
  'multiple' => '1',
  'name' => 'url',
  'provenance' => 'user',
  'required' => '0',
  'sql_index' => '0',
  'type' => 'url',
  'volatile' => '0'
}
,{
  'allow_null' => '1',
  'export_as_xml' => '0',
  'input_boxes' => 3,
  'input_cols' => 60,
  'input_ordered' => 0,
  'input_rows' => 10,
  'input_style' => 'short',
  'maxlength' => 255,
  'name' => 'nationality',
  'provenance' => 'user',
  'required' => '1',
  'set_name' => 'countries',
  'sql_index' => '0',
  'type' => 'namedset',
  'volatile' => '0'
}
,;
